name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Run tests (Go ${{ matrix.go }})
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test ./... -v -race
    strategy:
      matrix:
        go:
          - '1.24'
          - '1.25'
